//
// Copyright (c) 2026 viZPilot
//

#pragma once

//
// I took this from Little Kernel bootloader for Exynos 9610.
//
#define UFSHCI_REG_CAP 0x00
#define UFSHCI_REG_VER 0x08

//
// I took this from kernel-slsi for Motorola One Action
//
#define HCI_TXPRDT_ENTRY_SIZE		0x00
#define HCI_RXPRDT_ENTRY_SIZE		0x04
#define HCI_TO_CNT_DIV_VAL              0x08
#define HCI_1US_TO_CNT_VAL		0x0C
#define CNT_VAL_1US_MASK	0x3ff
#define HCI_INVALID_UPIU_CTRL		0x10
#define HCI_INVALID_UPIU_BADDR		0x14
#define HCI_INVALID_UPIU_UBADDR		0x18
#define HCI_INVALID_UTMR_OFFSET_ADDR	0x1C
#define HCI_INVALID_UTR_OFFSET_ADDR	0x20
#define HCI_INVALID_DIN_OFFSET_ADDR	0x24
#define HCI_VENDOR_SPECIFIC_IS		0x38
#define HCI_VENDOR_SPECIFIC_IE		0x3C
#define HCI_UTRL_NEXUS_TYPE		0x40
#define HCI_UTMRL_NEXUS_TYPE		0x44
#define HCI_E2EFC_CTRL			0x48
#define HCI_SW_RST			0x50
#define UFS_LINK_SW_RST	(1 << 0)
#define UFS_UNIPRO_SW_RST	(1 << 1)
#define UFS_SW_RST_MASK	(UFS_UNIPRO_SW_RST | UFS_LINK_SW_RST)
#define HCI_LINK_VERSION		0x54
#define HCI_IDLE_TIMER_CONFIG		0x58
#define HCI_RX_UPIU_MATCH_ERROR_CODE	0x5C
#define HCI_DATA_REORDER		0x60
#define HCI_MAX_DOUT_DATA_SIZE		0x64
#define HCI_UNIPRO_APB_CLK_CTRL		0x68
#define HCI_AXIDMA_RWDATA_BURST_LEN	0x6C
#define BURST_LEN(x)			((x) << 27 | (x))
#define WLU_EN				(1 << 31)
#define AXIDMA_RWDATA_BURST_LEN	(0xF)
#define HCI_GPIO_OUT			0x70
#define HCI_WRITE_DMA_CTRL		0x74
#define HCI_ERROR_EN_PA_LAYER		0x78
#define HCI_ERROR_EN_DL_LAYER		0x7C
#define HCI_ERROR_EN_N_LAYER		0x80
#define HCI_ERROR_EN_T_LAYER		0x84
#define HCI_ERROR_EN_DME_LAYER		0x88
#define HCI_UFSHCI_V2P1_CTRL			0X8C
#define IA_TICK_SEL				BIT(16)
#define HCI_REQ_HOLD_EN			0xAC

#define HCI_CLKSTOP_CTRL		0xB0
#define REFCLKOUT_STOP			BIT(4)
#define MPHY_APBCLK_STOP		BIT(3)
#define REFCLK_STOP			BIT(2)
#define UNIPRO_MCLK_STOP		BIT(1)
#define UNIPRO_PCLK_STOP		BIT(0)
#define CLK_STOP_ALL		(REFCLKOUT_STOP |\
					REFCLK_STOP |\
					UNIPRO_MCLK_STOP |\
					UNIPRO_PCLK_STOP)

#define HCI_FORCE_HCS			0xB4
#define REFCLKOUT_STOP_EN	BIT(11)
#define MPHY_APBCLK_STOP_EN	BIT(10)
#define UFSP_DRCG_EN		BIT(8)   //FMP
#define REFCLK_STOP_EN		BIT(7)
#define UNIPRO_PCLK_STOP_EN	BIT(6)
#define UNIPRO_MCLK_STOP_EN	BIT(5)
#define HCI_CORECLK_STOP_EN	BIT(4)
#define CLK_STOP_CTRL_EN_ALL	(UFSP_DRCG_EN |\
					MPHY_APBCLK_STOP_EN |\
					REFCLKOUT_STOP_EN |\
					REFCLK_STOP_EN |\
					UNIPRO_PCLK_STOP_EN |\
					UNIPRO_MCLK_STOP_EN)

#define HCI_FSM_MONITOR			0xC0
#define HCI_PRDT_HIT_RATIO		0xC4
#define HCI_DMA0_MONITOR_STATE		0xC8
#define HCI_DMA0_MONITOR_CNT		0xCC
#define HCI_DMA1_MONITOR_STATE		0xD0
#define HCI_DMA1_MONITOR_CNT		0xD4

#define HCI_UFS_AXI_DMA_IF_CTRL		0xF8
#define HCI_UFS_ACG_DISABLE		0xFC
#define HCI_UFS_ACG_DISABLE_EN		BIT(0)
#define HCI_IOP_ACG_DISABLE		0x100
#define HCI_IOP_ACG_DISABLE_EN		BIT(0)
#define HCI_MPHY_REFCLK_SEL		0x108
#define MPHY_REFCLK_SEL		BIT(0)
#define HCI_SMU_ABORT_MATCH_INFO		0x10C
#define HCI_DBR_DUPLICATION_INFO		0x120

#define HCI_DBR_TIMER_CONFIG		0x140
#define HCI_DBR_TIMER_ENABLE		0x144
#define HCI_DBR_TIMER_STATUS		0x148

#define HCI_UTRL_DBR_3_0_TIMER_EXPIRED_VALUE		0x150
#define HCI_UTRL_DBR_7_4_TIMER_EXPIRED_VALUE		0x154
#define HCI_UTRL_DBR_11_8_TIMER_EXPIRED_VALUE		0x158
#define HCI_UTRL_DBR_15_12_TIMER_EXPIRED_VALUE		0x15C
#define HCI_UTMRL_DBR_3_0_TIMER_EXPIRED_VALUE		0x160
